import '../select_saved_screen/widgets/selectsaved_item_widget.dart';import 'bloc/select_saved_bloc.dart';import 'models/select_saved_model.dart';import 'models/selectsaved_item_model.dart';import 'package:flutter/material.dart';import 'package:zonar_marketing__grapichs/core/app_export.dart';import 'package:zonar_marketing__grapichs/presentation/downloaded_tab_container_page/downloaded_tab_container_page.dart';import 'package:zonar_marketing__grapichs/presentation/home_page/home_page.dart';import 'package:zonar_marketing__grapichs/presentation/profile_page/profile_page.dart';import 'package:zonar_marketing__grapichs/presentation/saved_page/saved_page.dart';import 'package:zonar_marketing__grapichs/presentation/search_page/search_page.dart';import 'package:zonar_marketing__grapichs/widgets/app_bar/appbar_subtitle.dart';import 'package:zonar_marketing__grapichs/widgets/app_bar/appbar_title.dart';import 'package:zonar_marketing__grapichs/widgets/app_bar/custom_app_bar.dart';import 'package:zonar_marketing__grapichs/widgets/custom_bottom_bar.dart';import 'package:zonar_marketing__grapichs/widgets/custom_button.dart';import 'package:zonar_marketing__grapichs/presentation/delete_from_saved_dialog/delete_from_saved_dialog.dart';
// ignore_for_file: must_be_immutable
class SelectSavedScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<SelectSavedBloc>(create: (context) => SelectSavedBloc(SelectSavedState(selectSavedModelObj: SelectSavedModel()))..add(SelectSavedInitialEvent()), child: SelectSavedScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.black900, appBar: CustomAppBar(height: getVerticalSize(50), title: Padding(padding: getPadding(left: 25), child: Row(children: [AppbarSubtitle(text: "lbl_mark_all".tr, margin: getMargin(top: 8)), AppbarTitle(text: "lbl_saved".tr, margin: getMargin(left: 89))])), actions: [AppbarSubtitle(text: "lbl_delete".tr, margin: getMargin(left: 25, top: 20, right: 25, bottom: 11))]), body: Container(height: getVerticalSize(637), width: double.maxFinite, padding: getPadding(top: 23, bottom: 23), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 16, bottom: 14), child: BlocSelector<SelectSavedBloc, SelectSavedState, SelectSavedModel?>(selector: (state) => state.selectSavedModelObj, builder: (context, selectSavedModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(16));}, itemCount: selectSavedModelObj?.selectsavedItemList.length ?? 0, itemBuilder: (context, index) {SelectsavedItemModel model = selectSavedModelObj?.selectsavedItemList[index] ?? SelectsavedItemModel(); return SelectsavedItemWidget(model);});}))), CustomButton(height: getVerticalSize(50), width: getHorizontalSize(263), text: "lbl_delete".tr, margin: getMargin(bottom: 5), variant: ButtonVariant.OutlineBlack90019, fontStyle: ButtonFontStyle.PoppinsRegular16Red700_1, onTap: () {onTapDeleteOne(context);}, alignment: Alignment.bottomCenter)])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Search: return AppRoutes.searchPage; case BottomBarEnum.Saved: return AppRoutes.savedPage; case BottomBarEnum.Downloads: return AppRoutes.downloadedTabContainerPage; case BottomBarEnum.Me: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.homePage: return HomePage.builder(context); case AppRoutes.searchPage: return SearchPage.builder(context); case AppRoutes.savedPage: return SavedPage.builder(context); case AppRoutes.downloadedTabContainerPage: return DownloadedTabContainerPage.builder(context); case AppRoutes.profilePage: return ProfilePage.builder(context); default: return DefaultWidget();} } 
onTapDeleteOne(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: DeleteFromSavedDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: EdgeInsets.only(left: 0),)); } 
 }
